
- hosts: localhost
  gather_facts: no
  vars:
      gcp_project: valiant-hangout-310414
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/admin_/valiant-hangout-310414-08d733642027.json
      zone: "us-central1-a"
      region: "us-central1"
            
  tasks:
    - include_tasks: createinstance.yml
      with_items: 
            - {name : "apache" , address : "apache" , disk : "apache" }
            - {name : "nginx" , address : "nginx" , disk : "nginx" }

